
public enum EPacketType : short
{
    PT_NULL = 0,

    // Room operation
    PT_InRoom_InitData = 10,
    PT_InRoom_InitDataOK,
    PT_InRoom_TeamChange,
    PT_InRoom_StatusChange,
    PT_InRoom_StartLogin,
    PT_InRoom_Message,
    PT_InRoom_Ping,
    PT_InRoom_ForceSetting,
    PT_InRoom_KickPlayer,

    PT_InGame_PlayerLogin = 100,
    PT_InGame_InitData,
    PT_InGame_RequestData,
    PT_InGame_RequestInit,
    PT_InGame_PlayerBattleInfo,
    PT_InGame_BattleInfo,
    PT_InGame_BattleInfos,
    PT_InGame_BattleOver,
    PT_InGame_InitPackage,
    PT_InGame_PackageItem,
    PT_InGame_PackageIndex,
    PT_InGame_EquipedItem,
    PT_InGame_PutOnEquipment,
    PT_InGame_TakeOffEquipment,
    PT_InGame_EquipedIndex,
    PT_InGame_InitShortcut,
    PT_InGame_InitLearntSkills,
    PT_InGame_SetShortcut,
    PT_InGame_PlayerMoney,
    PT_InGame_CurSceneId,
    PT_InGame_MoneyType,
    PT_InGame_TerrainData,
    PT_InGame_TerrainDataOk,
	PT_InGame_CurTeamId,
	PT_InGame_HeartBeat,

	PT_InGame_OccupyArea = 200,
    PT_InGame_OccupyAreaArray,
    PT_InGame_LostArea,
    PT_InGame_AttackArea,
    PT_InGame_ExploredArea,
    PT_InGame_ExploredAreaArray,
    PT_InGame_MaskAreaArray,
    PT_InGame_MapArea,
    PT_InGame_MapAreaArray,
    PT_InGame_TownArea,
    PT_InGame_TownAreaArray,
    PT_InGame_CampArea,
    PT_InGame_CampAreaArray,

    PT_InGame_TreeArray = 300,
    PT_InGame_RailwayData,
    PT_InGame_FarmInfo,
    PT_InGame_MissionData,
    PT_InGame_InitStatus,
    PT_InGame_InitDataOK,
    PT_InGame_SceneObject,
    PT_InGame_MakeMask,
    PT_InGame_RemoveMask,
    PT_InGame_FastTransfer,
    PT_InGame_SwitchScene,
    PT_InGame_DelSceneObjects,

    //PlayerPlant
    PT_InGame_Plant_GetBack = 400,
    PT_InGame_Plant_PutOut,
    PT_InGame_Plant_VFTerrainTarget,
    PT_InGame_Plant_FarmInfo,
    PT_InGame_Plant_Water,
    PT_InGame_Plant_Clean,
    PT_InGame_Plant_Clear,
    PT_InGame_Plant_UpdateInfo,
    PT_InGame_Plant_UpdateInfoList,
    //player railway
    PT_InGame_Railway_AddPoint = 500,
    PT_InGame_Railway_PrePointChange,
    PT_InGame_Railway_NextPointChange,
    PT_InGame_Railway_Route,
    PT_InGame_Railway_GetOnTrain,
    PT_InGame_Railway_GetOffTrain,
    PT_InGame_Railway_DeleteRoute,
    PT_InGame_Railway_Recycle,
    PT_InGame_Railway_SetRouteTrain,
    PT_InGame_Railway_ChangeStationRot,
    PT_InGame_Railway_ResetPointName,
    PT_InGame_Railway_ResetRouteName,
    PT_InGame_Railway_ResetPointTime,
    PT_InGame_Railway_GetOffTrainEx,
    PT_InGame_Railway_AutoCreateRoute,
    PT_InGame_Railway_UpdateRoute,

    // accountitems
    PT_InGame_AccItems_CreateItem = 600,

    // Player Status
    PT_InGame_ApplyDamage = 700,
    PT_InGame_ApplyComfort,
    PT_InGame_ApplySatiation,
    PT_InGame_PlayerDeath,
    PT_InGame_PlayerRevive,
    PT_InGame_PlayerReset,
    PT_InGame_PlayerPosition,
    PT_InGame_PlayerRot,
    PT_InGame_PlayerState,
    PT_InGame_PlayerOnGround,
    PT_InGame_PlayerShootTarget,
    PT_InGame_GliderStatus,
    PT_InGame_ParachuteStatus,
    PT_InGame_JetPackStatus,

    // Item
    PT_InGame_DeadObjItem = 800,
    PT_InGame_TowerItem,
    PT_InGame_StaticItem,
    PT_InGame_GetAllDeadObjItem,
    PT_InGame_GetDeadObjItem,
    PT_InGame_PutItem,
    PT_InGame_PutOutTower,
    PT_InGame_PutOutFlag,
    PT_InGame_MissionItem,
    PT_InGame_UseItem,
    PT_InGame_GetItemListBack,
    PT_InGame_GetItemBack,
	PT_InGame_GetLootItemBack,
    PT_InGame_GetColonyBack,
    PT_InGame_GetOnVehicle,
    PT_InGame_GetOffVehicle,
    PT_InGame_RepairVehicle,
    PT_InGame_ChargeVehicle,
    PT_InGame_TowerRefill,
    PT_InGame_PackageSplit,
    PT_InGame_PackageDelete,
    PT_InGame_PackageSort,
    PT_InGame_ExchangeItem,
    PT_InGame_RemoveNewFlag,
    PT_InGame_MissionMoveAircraft,
    PT_InGame_Mission953,
    PT_InGame_LanguegeSkill,
	PT_InGame_PreGetItemBack,

	PT_InGame_PublicStorageStore = 900,
    PT_InGame_PublicStorageExchange,
    PT_InGame_PublicStorageFetch,
    PT_InGame_PublicStorageDelete,
    PT_InGame_PublicStorageSplit,
    PT_InGame_PublicStorageSort,
    PT_InGame_PublicStorageIndex,

    PT_InGame_PersonalStorageStore,
    PT_InGame_PersonalStorageExchange,
    PT_InGame_PersonalStorageFetch,
    PT_InGame_PersonalStroageDelete,
    PT_InGame_PersonalStorageSplit,
    PT_InGame_PersonalStorageSort,
    PT_InGame_PersonalStorageIndex,

    PT_InGame_CreateBuilding = 1000,
    PT_InGame_ItemObject,
    PT_InGame_ItemObjectList,
    PT_InGame_ItemRemove,
    PT_InGame_NewItem,
    PT_InGame_NewItemList,
    PT_InGame_CreateMapObj,
    PT_InGame_PackageItemCost,
    PT_InGame_ItemAttrChanged,
    PT_InGame_EquipItemCost,
    PT_InGame_WeaponReload,
    PT_InGame_GunEnergyReload,
    PT_InGame_BatteryEnergyReload,
    PT_InGame_JetPackEnergyReload,
    PT_InGame_WeaponDurability,
    PT_InGame_ArmorDurability,
    PT_InGame_CreateSceneBox,
    PT_InGame_CreateSceneItem,
    //share
    PT_InGame_Turn = 1100,
    PT_InGame_GameStarted,
    // Msg
    PT_InGame_SendMsg = 1200,

    // Mission
    PT_InGame_MissionPackageIndex = 1300,
    PT_InGame_SyncMission,
    PT_InGame_NewMission,
    PT_InGame_AccessMission,
    PT_InGame_DeleteMission,
    PT_InGame_InitMission,
    PT_InGame_MissionMonsterPos,
    PT_InGame_MissionFollowPos,
    PT_InGame_MissionDiscoveryPos,
    PT_InGame_MissionItemUsePos,
    PT_InGame_CompleteTarget,
    PT_InGame_CompleteMission,
    PT_InGame_ModifyMissionFlag,
    PT_InGame_MissionFailed,
    PT_InGame_AddNpcToColony,
    PT_InGame_ComMisTest,
    PT_InGame_MissionUseItem,
    PT_InGame_ModifyQuestVariable,
    PT_InGame_SetMission,
    PT_InGame_SetCollectItemID,

    PT_InGame_TowerMonsterLeft,
    PT_InGame_MissionKillMonster,
    PT_InGame_MissionTowerDefense,
    PT_InGame_TDInitData,
    PT_InGame_TDStartInfo,
    PT_InGame_TDInfo,
    PT_InGame_TDMonsterDeath,
    PT_InGame_MonsterBook,
    PT_InGame_EntityReach,
    PT_InGame_RequestAdMissionData,

    // Team
    PT_InGame_CreateTeam = 1400,
    PT_InGame_JoinTeam,
    PT_InGame_ApproveJoin,
    PT_InGame_DenyJoin,
    PT_InGame_Invitation,
    PT_InGame_AcceptJoinTeam,
    PT_InGame_KickSB,
    PT_InGame_LeaderDeliver,
    PT_InGame_QuitTeam,
    PT_InGame_TeamInfo,
    PT_InGame_DissolveTeam,

    // Skill
    PT_InGame_MergeSkillList = 1500,
    PT_InGame_MetalScanList,
    PT_InGame_MergeSkill,
    PT_InGame_CancelMerge,
    PT_InGame_SynthesisSuccess,
    PT_InGame_SkillCast,
    PT_InGame_SkillShoot,
    PT_InGame_SkillTakeEffect,
    PT_InGame_SkillVoxel,
    PT_InGame_SkillVoxelRange,
    PT_InGame_SkillBlockRange,
    PT_InGame_WaterPitcher,
    PT_InGame_WaterPump,
    PT_InGame_SKSyncAttr,
    PT_InGame_SKStartSkill,
    PT_InGame_SKStopSkill,
    PT_InGame_SKBLoop,
    PT_InGame_SKSyncInitAttrs,
    PT_InGame_SKSendBaseAttrs,
    PT_InGame_SKFellTree,
    PT_InGame_SKDigTerrain,
    PT_InGame_SKChangeTerrain,
    PT_InGame_SkOnDamage,
    PT_InGame_AbnormalConditionStart,
    PT_InGame_AbnormalConditionEnd,
    PT_InGame_AbnormalCondition,
    PT_InGame_Jump,

    //do action
    PT_InGame_SKDAVVF = 1600,
    PT_InGame_SKDAVFNS,
    PT_InGame_SKDANO,
    PT_InGame_SKDAV,
    PT_InGame_SKDAVVN,
    PT_InGame_SKDAVQNS,
    PT_InGame_SKDAVQ,
    PT_InGame_SKDAS,
    PT_InGame_SKDAVQS,
    PT_InGame_SKDAVVNN,
    PT_InGame_SKDAN,
    PT_InGame_SKDAB,
    PT_InGame_SKDAVQN,
    PT_InGame_SKDAVFVFS,
    PT_InGame_SKDAVQSN,
    PT_InGame_SKDAEndAction,
    PT_InGame_SKDAEndImmediately,
    PT_InGame_SKDAQueryEntityState,
    PT_InGame_SKDAVQSNS, //lz-2017.02.15 坐骑用新增的数据类型

    //ik
    PT_InGame_SKIKPos = 1700,
    //skilltree
    PT_InGame_SKTLevelUp = 1800,
    // Admin
    PT_InGame_AddBlackList = 1900,
    PT_InGame_DelBlackList,
    PT_InGame_ClearBlackList,
    PT_InGame_AddAssistant,
    PT_InGame_DelAssistant,
    PT_InGame_ClearAssistant,
    PT_InGame_BuildLock,
    PT_InGame_BuildUnLock,
    PT_InGame_ClearBuildLock,
    PT_InGame_ClearVoxel,
    PT_InGame_ClearAllVoxel,
    PT_InGame_AreaLock,
    PT_InGame_AreaUnLock,
    PT_InGame_BlockLock,
    PT_InGame_Kick,
    PT_InGame_LoginBan,


    // Shop
    PT_InGame_InitShop = 2000,
    PT_InGame_Buy,
    PT_InGame_Repurchase,
    PT_InGame_Sell,
    PT_InGame_ShopIndex,
    PT_InGame_RepurchaseIndex,
    PT_InGame_ChangeCurrency,

    PT_InGame_LostController = 2100,
    PT_InGame_SetController,

    //armor
    PT_InGame_SyncArmorInfo = 2200,
    PT_InGame_SwitchArmorSuit,
    PT_InGame_EquipArmorPart,
    PT_InGame_RemoveArmorPart,
    PT_InGame_SwitchArmorPartMirror,
    PT_InGame_SyncArmorPartPos,
    PT_InGame_SyncArmorPartRot,
    PT_InGame_SyncArmorPartScale,

    // Build Block
    PT_InGame_BlockUndo = 2300,
    PT_InGame_BlockRedo,
    PT_InGame_TreeInfo,
    PT_InGame_GrassInfo,
	PT_InGame_ClearGrass,
	PT_InGame_ClearTree,

    // Random Item
    PT_InGame_RandomItem = 2400,
	PT_InGame_RandomItemRare,
	PT_InGame_RandomIsoCode,
	PT_InGame_RandomItemRareAry,
	PT_InGame_RandomIsoCodeAry,
	PT_InGame_RandomIsoObj,
    PT_InGame_RandomItemFetch,
    PT_InGame_RandomItemFetchAll,
    // Random Feces
    PT_InGame_RandomFeces,
    // --new clicked
    PT_InGame_RandomItemClicked,
    PT_InGame_RandomItemDestroy,
	PT_InGame_RandomItemDestroyList,

    PT_InGame_ReviveSB,
    PT_InGame_ApprovalRevive,

    PT_InGame_TowerDefense,
    PT_InGame_KillMonster,
	
	//dungen
	PT_InGame_EnterDungeon,
	PT_InGame_ExitDungeon,
	PT_InGame_UploadDungeonSeed,
	PT_InGame_GenDunEntrance,
	PT_InGame_GenDunEntranceList,
	PT_InGame_RemoveDunEntrance,
	PT_InGame_InitWhenSpawn,

    // AIGroup
    PT_AG_SpawnAIGroupMemberAtPoint = 2500,
    PT_AG_ClearHatredAll,
    PT_AG_ClearMoveAndRotation,
    PT_AG_ActivateSingleBehave,
    PT_AG_MoveToPositionArmy,
    PT_AG_MoveToPosition,
    PT_AG_MoveToPositionFree,
    PT_AG_RunawayForPosition,
    PT_AG_SetIsSpawned,
    PT_AG_RequestIsSpawned,
    PT_AG_InitData,
    //mapobj
    PT_MO_InsertItemList = 2600,
    PT_MO_RequestItemList,
    PT_MO_GetAllItem,
    PT_MO_GetItem,
    PT_MO_ModifyItemList,
    PT_MO_RemoveItem,
    PT_MO_StartRepair,
    PT_MO_StopRepair,
    PT_MO_SyncRepairTime,
    PT_MO_Destroy,
    //itemfetch
    PT_IF_InitData,
    PT_IF_SyncItems,
    //item
    PT_ITEM_InitData,
    PT_ITEM_OpenDoor,
    PT_ITEM_ShutDoor,
    //creation
    PT_CR_InitData = 2700,
    PT_CR_Death,
    PT_CR_SkillCast,
    PT_CR_SkillCastShoot,
    PT_CR_SkillTakeEffect,
    PT_CR_Turn,
    PT_CR_ChargeFuel,
    PT_CR_ApplyHpChange,
    PT_CR_SyncEnergyDelta,
    PT_CR_SyncPos,
    PT_CR_SyncRot,
    PT_CR_SyncVelocity,
    PT_CR_SyncExtendInput,
    PT_CR_SyncAimPoint,
    PT_CR_SyncAngularVelocity,
    PT_CR_SyncApply,

    //colonyMgr
    PT_CL_MGR_InitData = 2800,

    //colony
    PT_CL_InitData,
    PT_CL_Turn,
    PT_CL_Recycle,
    PT_CL_Repair,
    PT_CL_SyncColonyDurability,
    PT_CL_RemoveColonyEntity,
    PT_CL_BeginRecycle,
    PT_CL_EndRecycle,
    PT_CL_RepairStart,
    PT_CL_RepairEnd,
    PT_CL_SyncCreationFuel,
    PT_CL_SyncCreationHP,
    PT_CL_SyncItem,

    //colony assembly
    PT_CL_InitDataAssembly,
    PT_CL_ASB_LevelUp,
    PT_CL_ASB_LevelUpStart,
    PT_CL_ASB_QueryTime,
    PT_CL_ASB_HideShield,
    PT_CL_ASB_ShowTip,
    //colony dwelling
    PT_CL_InitDataDwellings,
    PT_CL_DWL_SyncNpc,
    //colony enhance
    PT_CL_InitDataEnhance,
    PT_CL_EHN_SetItem,
    PT_CL_EHN_Start,
    PT_CL_EHN_Stop,
    PT_CL_EHN_Fetch,
    PT_CL_EHN_SyncTime,
    PT_CL_EHN_End,
    //colony factory
    PT_CL_InitDataFactory,
    PT_CL_FCT_Compoud,
    PT_CL_FCT_Fetch,
    PT_CL_FCT_IsReady,
    PT_CL_FCT_AddCompoudList,
    PT_CL_FCT_RemoveCompoudList,
    PT_CL_FCT_SyncItem,
    PT_CL_FCT_SyncAllItems,
    PT_CL_FCT_GenFactoryCancel,
    //colony farm
    PT_CL_InitDataFarm,
    PT_CL_FARM_SetPlantSeed,
    PT_CL_FARM_SetPlantTool,
    PT_CL_FARM_SetSequentialActive,
    PT_CL_FARM_SetAutoPlanting,
    PT_CL_FARM_FetchSeedItem,
    PT_CL_FARM_FetchToolItem,
    PT_CL_FARM_GetSeed,
    PT_CL_FARM_DeleteSeed,
    PT_CL_FARM_DeletePlantTool,
    PT_CL_FARM_RestoreWater,
    PT_CL_FARM_RestoreClean,
    PT_CL_FARM_RestoreGetBack,
    //powerplant
    PT_CL_InitDataPowerPlanet,
    PT_CL_POW_AddChargItem,
    PT_CL_POW_GetChargItem,
    //ppcoal
    PT_CL_InitDataPPCoal,
    PT_CL_PPC_AddFuel,
    PT_CL_PPC_WorkedTime,
	PT_CL_PPC_NoPower,
	//PT_CL_PPC_ShowElectric,
    //recycle
    PT_CL_InitDataRecycle,
    PT_CL_RCY_SetItem,
    PT_CL_RCY_Start,
    PT_CL_RCY_Stop,
    PT_CL_RCY_FetchMaterial,
    PT_CL_RCY_FetchItem,
    PT_CL_RCY_SyncTime,
    PT_CL_RCY_SyncRecycleItem,
    PT_CL_RCY_End, //lz-2016.12.27 回收得到的东西放到玩家背包
    PT_CL_RCY_MatsToStorage, //lz-2016.12.27 回收得到的东西放到基地仓库
    PT_CL_RCY_MatsToResult, //lz-2016.12.27 回收得到的东西放成物品球
    //storage
    PT_CL_InitDataStorage,
    PT_CL_STO_Delete,
    PT_CL_STO_Store,
    PT_CL_STO_Fetch,
    PT_CL_STO_Exchange,
    PT_CL_STO_Split,
    PT_CL_STO_Sort,
    PT_CL_STO_SyncItemList,
    //repair
    PT_CL_InitDataRepair,
    PT_CL_RPA_SetItem,
    PT_CL_RPA_Start,
    PT_CL_RPA_Stop,
    PT_CL_RPA_End,
    PT_CL_RPA_FetchItem,
    PT_CL_RPA_SyncTime,
    //processing
    PT_CL_InitDataProcessing,
    PT_CL_PRC_AddItem,
	PT_CL_PRC_RemoveItem,
	PT_CL_PRC_AddNpc,
    PT_CL_PRC_RemoveNpc,
	PT_CL_PRC_SetRound,
    PT_CL_PRC_SetAuto,
    PT_CL_PRC_Start,
    PT_CL_PRC_Stop,
    PT_CL_PRC_InitResultPos,
    PT_CL_PRC_GenResult,
	PT_CL_PRC_FinishToStorage,
	PT_CL_PRC_SyncAllCounter,
    //Trade
    PT_CL_InitDataTrade,
//  PT_CL_TRD_AddTown,
//	PT_CL_TRD_RemoveTown,
//  PT_CL_TRD_TryTrade,
//  PT_CL_TRD_RefreshItem,
	PT_CL_TRD_RequestShop,
	PT_CL_TRD_BuyItem,
	PT_CL_TRD_SellItem,
	PT_CL_TRD_RepurchaseItem,
	PT_CL_TRD_UpdateBuyItem,
	PT_CL_TRD_UpdateRepurchaseItem,
	PT_CL_TRD_UpdateMoney,
    //check
    PT_CL_InitDataCheck,
    PT_CL_CHK_FindMachine,
    PT_CL_CHK_SetDiagnose,
    PT_CL_CHK_TryStart,
    PT_CL_CHK_RemoveDeadNpc,
    PT_CL_CHK_CheckFinish,
    //treat
    PT_CL_InitDataTreat,
    PT_CL_TRT_FindMachine,
    PT_CL_TRT_SetTreat,
    PT_CL_TRT_TryStart,
    PT_CL_TRT_StartTreatCounter,
    PT_CL_TRT_SetItem,
    PT_CL_TRT_DeleteItem,
    PT_CL_TRT_RemoveDeadNpc,
    PT_CL_TRT_TreatFinish,
    PT_CL_TRT_ResetNpcToCheck,
    //tent
    PT_CL_InitDataTent,
    PT_CL_TET_FindMachine,
    PT_CL_TET_TryStart,
    PT_CL_TET_SetTent,
    PT_CL_TET_RemoveDeadNpc,
    PT_CL_TET_TentFinish,
    //train
    PT_CL_InitDataTrain,
    PT_CL_TRN_StartSkillTraining,
    PT_CL_TRN_StartAttributeTraining,
    PT_CL_TRN_SetInstructor,
    PT_CL_TRN_SetTrainee,
    PT_CL_TRN_SkillTrainFinish,
    PT_CL_TRN_AttributeTrainFinish,
    PT_CL_TRN_StopTraining,
	PT_CL_TRN_SyncCounter,
    
	PT_CL_Counter_Tick,


    //colony npc
    PT_CL_CLN_InitData = 3200,
    PT_CL_CLN_SetState,
    PT_CL_CLN_SetDwellingsID,
    PT_CL_CLN_SetWorkRoomID,
    PT_CL_CLN_SetOccupation,
    PT_CL_CLN_SetWorkMode,
//    PT_CL_CLN_SetGuardPos,
    PT_CL_CLN_PlantGetBack,
    PT_CL_CLN_RemoveNpc,
    PT_CL_CLN_PlantPutOut,
    PT_CL_CLN_PlantUpdateInfo,
    PT_CL_CLN_PlantClear,
    PT_CL_CLN_PlantWater,
    PT_CL_CLN_PlantClean,
    PT_CL_CLN_SetProcessingIndex,
    PT_CL_CLN_SetIsProcessing,

    // NPC
    PT_NPC_CreateAd = 3300,
    PT_NPC_CreateStRd,
    PT_NPC_CreateSt,
    PT_NPC_CreateTown,
    PT_NPC_InitData,
    PT_NPC_Dismiss,
    PT_NPC_Recruit,
    PT_NPC_SetRadius,
    PT_NPC_HPChange,
    PT_NPC_Death,
    PT_NPC_Turn,
    PT_NPC_PutOnEquip,
    PT_NPC_TakeOffEquip,
    PT_NPC_UseItem,
    PT_NPC_GetItem,
    PT_NPC_DeleteItem,
    PT_NPC_Revive,
    PT_NPC_WorkState,
    PT_NPC_WorkItemFetch,
    PT_NPC_Move,
    PT_NPC_ForceMove,
    PT_NPC_RotY,
    PT_NPC_MissionFlag,
    PT_NPC_PacageIndex,
    PT_NPC_EquipIndex,
    PT_NPC_Money,
    PT_NPC_SyncTeamID,
    PT_NPC_Equips,
    PT_NPC_Items,
    PT_NPC_Mission,
    PT_NPC_ResetPosition,
    PT_NPC_Destroy,
    PT_NPC_MissionState,
    PT_NPC_ServentRevive,
    PT_NPC_ForcedServant,
    //npcai
    PT_NPC_RequestAiOp,
    PT_NPC_Mount,
    PT_NPC_UpdateCampsite,
    PT_NPC_State,
    PT_NPC_ExternData,
    PT_NPC_Skill,
    PT_NPC_DeleteAllItem,
    PT_NPC_SortPackage,
    PT_NPC_SelfUseItem,
    PT_NPC_CreateAdMainNpc,
	PT_NPC_AddEnemyLock,
	PT_NPC_RemoveEnemyLock,
	PT_NPC_ClearEnemyLocked,

	// AI Tower
	PT_Tower_InitData = 3400,
    PT_Tower_Move,
    PT_Tower_Target,
    PT_Tower_Turn,
    PT_Tower_Cost,
    PT_Tower_AimPosition,
    PT_Tower_Fire,
	PT_Tower_LostEnemy,

    // AI Static Object
    PT_SO_InitData,

    // AI Tower Defense
    PT_TD_InitData,
    PT_TD_End,
    PT_TD_Wave,

    PT_AI_SpawnPos,
    PT_AI_SetFixActive,

    // AI
    PT_AI_SpawnAI,
    PT_AI_SpawnGroupAI,
    PT_AI_NativeTower,
    PT_AI_Gift,
    PT_AI_NativeStatic,
    PT_AI_Death,
    PT_AI_ApplyHpChange,
    PT_AI_InitData,
    PT_AI_AnimatorState,
    PT_AI_SetRadius,
    PT_AI_Move,
    PT_AI_RotY,
    PT_AI_IKTarget,
    PT_AI_Animation,
    PT_AI_Equipment,
    PT_AI_Turn,
    PT_AI_RifleAim,
    PT_AI_IKPosition,
    PT_AI_IKPosWeight,
    PT_AI_IKRotation,
    PT_AI_IKRotWeight,

    PT_AI_BoolString,
    PT_AI_BoolInt,
    PT_AI_VectorString,
    PT_AI_VectorInt,
    PT_AI_IntString,
    PT_AI_IntInt,
    PT_AI_LayerWeight,
    PT_AI_LookAtPos,
    PT_AI_LookAtWeight,
    PT_AI_SetBool,
    PT_AI_SetTrigger,
    PT_AI_SetMoveMode,
    PT_AI_HoldWeapon,
    PT_AI_SwitchHoldWeapon,
    PT_AI_SwordAttack,
    PT_AI_TwoHandWeaponAttack,
    PT_AI_SetIKAim,
    PT_AI_Fadein,
    PT_AI_Fadeout,
	PT_AI_AvatarData,
	PT_AI_ExternData,

	PT_Common_ColorIndex = 3700,
    PT_Common_ServerInfo,
    PT_Common_RandomTownData,
    PT_Common_InitGameTimer,
    PT_Common_ElapseSpeedShift,
    PT_Common_GameTimer,
    PT_Common_InitWeather,
    PT_Common_InitAdminData,
    PT_Common_BlockData,
    PT_Common_VoxelData,
    PT_Common_TownCreate,
    PT_Common_NativeTowerDestroyed,
    PT_Common_WeatherChange,
    PT_Common_FoundMapLable,
    PT_Common_TownDoodad,
    PT_Common_NativeTowerCreate,
	PT_Common_ScenarioId,
	PT_Common_TownDestroyed,
	PT_Common_InitTownPos,

    // Item
    PT_Item_Package = 3800,
    PT_Item_Equip,
    PT_Item_Storage,

    PT_Common_Item,
    PT_Common_ItemList,

    // WorkShop
    PT_Common_RequestUGC = 3900,
    PT_Common_UGCUpload,
    PT_Common_UGCDownloaded,
    PT_Common_WorkshopShared,
    PT_Common_UGCItem,
    PT_Common_UGCSkill,
    PT_Common_UGCData,
    PT_Common_UGCList,
    PT_Common_InvalidUGC,
    PT_Common_PreUpload,
    PT_Common_DownTimeOut,
    PT_Common_StartSendFile,
    PT_Common_SendFile,
    PT_Common_GetRandIsoFileIds,
    PT_Common_SendRandIsoFileIds,
    PT_Common_ExportRandIso,
    PT_Common_SendRandIsoHash,
    PT_Common_IsoExportSuccessed,

    // Error Msg
    PT_Common_ErrorMsg = 4000,
    PT_Common_ErrorMsgBox,
    PT_Common_ErrorMsgCode,

    PT_Test_AddItem = 4100,
    PT_Test_AddEquipment,
    PT_Test_PutOnEquipment,
    PT_Test_MoveNpc,

    PT_CustomEvent_Death = 4200,
    PT_CustomEvent_Damage,
    PT_CustomEvent_UseItem,
    PT_CustomEvent_PutoutItem,

    PT_Custom_CheckPos = 4300,
    PT_Custom_CheckRot,
    PT_Custom_CheckDist3D,
    PT_Custom_CheckDist2D,
    PT_Custom_CheckLookAt3D,
    PT_Custom_CheckLookAt2D,
    PT_Custom_CheckOwerItem,
    PT_Custom_CheckAttribute,
    PT_Custom_CheckEquip,
    PT_Custom_CheckWorld,
    PT_Custom_CheckResult,

    PT_Custom_AddQuest = 4400,
    PT_Custom_RemoveQuest,
    PT_Custom_StartAnimation,
    PT_Custom_StopAnimation,
    PT_Custom_SetPos,
    PT_Custom_ModifyPackage,
    PT_Custom_SetVariable,
    PT_Custom_ModifyStat,
    PT_Custom_Kill,
    PT_Custom_CreateObject,
    PT_Custom_RemoveObject,
    PT_Custom_RemoveSpecObject,
    PT_Custom_EnableSpawn,
    PT_Custom_DisableSpawn,
    PT_Custom_OrderVector,
    PT_Custom_OrderTarget,
    PT_Custom_CancelOrder,
    PT_Custom_FastTravel,

    //reputation
    PT_Reputation_SetValue = 4500,
    PT_Reputation_SetExValue,
    PT_Reputation_SetActive,
    PT_Reputation_SyncValue,
    PT_Custom_AddChoice,
	PT_CheatingChecked,

    //Ride monster
    PT_Mount_ReqMonsterCtrl,
    PT_Mount_AddMountMonster,
    PT_Mount_DelMountMonster,
    PT_Mount_SyncPlayerRot,

    //gm
    PT_GM_Statistics = 5500,

    //gameend
    PT_InGame_GameEnd = 6000,

    PT_MAX
}
